// Code generated by "stringer -type=Behavior"; DO NOT EDIT.

package item

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Solid-1]
	_ = x[CanStackOnTop-2]
	_ = x[CanSitOnTop-3]
	_ = x[CanStandOnTop-4]
	_ = x[CanLayOnTop-5]
	_ = x[CustomDataNumericOnOff-6]
	_ = x[RequiresTouchingForInteraction-7]
	_ = x[CustomDataTrueFalse-8]
	_ = x[PublicSpaceObject-9]
	_ = x[ExtraParameter-10]
	_ = x[Dice-11]
	_ = x[CustomDataOnOff-12]
	_ = x[CustomDataNumericState-13]
	_ = x[Teleporter-14]
	_ = x[RequiresRightsForInteraction-15]
	_ = x[Gate-16]
	_ = x[PrizeTrophy-17]
	_ = x[Roller-18]
	_ = x[Redeemable-19]
	_ = x[SoundMachine-20]
	_ = x[SoundMachineSampleSet-21]
	_ = x[Jukebox-22]
	_ = x[WallItem-23]
	_ = x[PostIt-24]
	_ = x[Decoration-25]
	_ = x[WheelOfFortune-26]
	_ = x[RoomDimmer-27]
	_ = x[Present-28]
	_ = x[Photo-29]
	_ = x[PlaceRollerOnTop-30]
	_ = x[Invisible-31]
	_ = x[Effect-32]
	_ = x[RedirectRotation0-33]
	_ = x[RedirectRotation2-34]
	_ = x[RedirectRotation4-35]
	_ = x[SongDisk-36]
	_ = x[PetWaterBowl-37]
	_ = x[PetFood-38]
	_ = x[PetCatFood-39]
	_ = x[PetDogFood-40]
	_ = x[PetCrocFood-41]
	_ = x[PrivateFurniture-42]
}

const _Behavior_name = "InvalidSolidCanStackOnTopCanSitOnTopCanStandOnTopCanLayOnTopCustomDataNumericOnOffRequiresTouchingForInteractionCustomDataTrueFalsePublicSpaceObjectExtraParameterDiceCustomDataOnOffCustomDataNumericStateTeleporterRequiresRightsForInteractionGatePrizeTrophyRollerRedeemableSoundMachineSoundMachineSampleSetJukeboxWallItemPostItDecorationWheelOfFortuneRoomDimmerPresentPhotoPlaceRollerOnTopInvisibleEffectRedirectRotation0RedirectRotation2RedirectRotation4SongDiskPetWaterBowlPetFoodPetCatFoodPetDogFoodPetCrocFoodPrivateFurniture"

var _Behavior_index = [...]uint16{0, 7, 12, 25, 36, 49, 60, 82, 112, 131, 148, 162, 166, 181, 203, 213, 241, 245, 256, 262, 272, 284, 305, 312, 320, 326, 336, 350, 360, 367, 372, 388, 397, 403, 420, 437, 454, 462, 474, 481, 491, 501, 512, 528}

func (i Behavior) String() string {
	if i < 0 || i >= Behavior(len(_Behavior_index)-1) {
		return "Behavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Behavior_name[_Behavior_index[i]:_Behavior_index[i+1]]
}
