// Code generated by "stringer -type=tileState"; DO NOT EDIT.

package room

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Accessible-0]
	_ = x[Inaccessible-1]
}

const _TileState_name = "AccessibleInaccessible"

var _TileState_index = [...]uint8{0, 10, 22}

func (i TileState) String() string {
	if i < 0 || i >= TileState(len(_TileState_index)-1) {
		return "tileState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileState_name[_TileState_index[i]:_TileState_index[i+1]]
}
